INSERT INTO photoVotes (photoID) VALUE 0
INSERT INTO photoVotes (photoID) VALUE 1
INSERT INTO photoVotes (photoID) VALUE 2
INSERT INTO photoVotes (photoID) VALUE 3
INSERT INTO photoVotes (photoID) VALUE 4
INSERT INTO photoVotes (photoID) VALUE 5
INSERT INTO photoVotes (photoID) VALUE 6
INSERT INTO photoVotes (photoID) VALUE 7
INSERT INTO photoVotes (photoID) VALUE 8
INSERT INTO photoVotes (photoID) VALUE 9
INSERT INTO photoVotes (photoID) VALUE 10
INSERT INTO photoVotes (photoID) VALUE 11
INSERT INTO photoVotes (photoID) VALUE 12
INSERT INTO photoVotes (photoID) VALUE 13
INSERT INTO photoVotes (photoID) VALUE 14
INSERT INTO photoVotes (photoID) VALUE 15
INSERT INTO photoVotes (photoID) VALUE 16
INSERT INTO photoVotes (photoID) VALUE 17
INSERT INTO photoVotes (photoID) VALUE 18
INSERT INTO photoVotes (photoID) VALUE 19
INSERT INTO photoVotes (photoID) VALUE 20
INSERT INTO photoVotes (photoID) VALUE 21
INSERT INTO photoVotes (photoID) VALUE 22
INSERT INTO photoVotes (photoID) VALUE 23
INSERT INTO photoVotes (photoID) VALUE 24
INSERT INTO photoVotes (photoID) VALUE 25
INSERT INTO photoVotes (photoID) VALUE 26
INSERT INTO photoVotes (photoID) VALUE 27
INSERT INTO photoVotes (photoID) VALUE 28
INSERT INTO photoVotes (photoID) VALUE 29
INSERT INTO photoVotes (photoID) VALUE 30
INSERT INTO photoVotes (photoID) VALUE 31
INSERT INTO photoVotes (photoID) VALUE 32
INSERT INTO photoVotes (photoID) VALUE 33
INSERT INTO photoVotes (photoID) VALUE 34
INSERT INTO photoVotes (photoID) VALUE 35
INSERT INTO photoVotes (photoID) VALUE 36
INSERT INTO photoVotes (photoID) VALUE 37
INSERT INTO photoVotes (photoID) VALUE 38
INSERT INTO photoVotes (photoID) VALUE 39
INSERT INTO photoVotes (photoID) VALUE 40
INSERT INTO photoVotes (photoID) VALUE 41
INSERT INTO photoVotes (photoID) VALUE 42
INSERT INTO photoVotes (photoID) VALUE 43
INSERT INTO photoVotes (photoID) VALUE 44
INSERT INTO photoVotes (photoID) VALUE 45
INSERT INTO photoVotes (photoID) VALUE 46
INSERT INTO photoVotes (photoID) VALUE 47
INSERT INTO photoVotes (photoID) VALUE 48
INSERT INTO photoVotes (photoID) VALUE 49
